# kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 30000  # Backend NodePort
    hostPort: 30000
    protocol: TCP
  - containerPort: 30001  # Frontend NodePort
    hostPort: 30001
    protocol: TCP
  - containerPort: 80     # Ingress
    hostPort: 80
    protocol: TCP
  - containerPort: 443    # Ingress HTTPS
    hostPort: 443
    protocol: TCP
